<?php

namespace CampaBundle\Repository;

/**
 * AuditoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
