<?php

namespace CampaBundle\Repository;

/**
 * CabanaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabanaRepository extends \Doctrine\ORM\EntityRepository
{
}
