<?php

namespace CampaBundle\Repository;

/**
 * DistritosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistritosRepository extends \Doctrine\ORM\EntityRepository
{
}
