<?php

namespace CampaBundle\Repository;

/**
 * JovenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JovenesRepository extends \Doctrine\ORM\EntityRepository
{
}
