<?php

namespace CampaBundle\Repository;

/**
 * PagosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagosRepository extends \Doctrine\ORM\EntityRepository
{
}
